apiVersion: v1
kind: Service
metadata:
  name: easynotes-service
  labels:
    role: frontend
spec:
  selector:
    role: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort