apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    role: db
spec:
  replicas: 1
  selector:
    matchLabels:
      role: db
  template:
    metadata:
      labels:
        role: db
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        volumeMounts:
          - mountPath: /var/lib/mongo
            name: mdb-data
      volumes:
      - name: mdb-data
      restartPolicy: Always