apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    role: db
spec:
  selector:
    role: db
  ports:
  - protocol: TCP 
    port: 27017
    targetPort: 27017
  type: ClusterIP