apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: easynotes-networkpolicy
  namespace: default
spec:
  podSelector:
    matchLabels:
      role: db
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: frontend
  policyTypes:
  - Ingress