apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "helm-chart.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.easynotesnaming.nameOverride }}